spring:
  profiles:
    active: default

  datasource:
    url: jdbc:h2:file:./src/main/resources/h2-database/musinsa
    username: sa
    password: pass
    driver-class-name: org.h2.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:backup.sql

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false