-- H2 2.3.230;
;
DROP TABLE IF EXISTS "PUBLIC"."PRODUCT";
DROP TABLE IF EXISTS "PUBLIC"."CATEGORY";
DROP TABLE IF EXISTS "PUBLIC"."BRAND";

CREATE USER IF NOT EXISTS "SA" SALT 'cb8c65dac098e4a7' HASH '0eeaffd747971f398998f1f8917f6506d17ef726b726be81160117d5380abea5' ADMIN;
CREATE CACHED TABLE "PUBLIC"."BRAND"(
    "BRAND_IDX" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 5) NOT NULL,
    "CREATE_DT" TIMESTAMP(6) NOT NULL,
    "DELETE_DT" TIMESTAMP(6),
    "MODIFY_DT" TIMESTAMP(6) NOT NULL,
    "USE_YN" BOOLEAN NOT NULL,
    "VERSION" BIGINT NOT NULL,
    "BRAND_DESC" CHARACTER VARYING(255),
    "BRAND_IMAGE" CHARACTER VARYING(255),
    "BRAND_NAME" CHARACTER VARYING(255)
);
ALTER TABLE "PUBLIC"."BRAND" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("BRAND_IDX");

INSERT INTO "PUBLIC"."BRAND" VALUES
                                 (1, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'brandA', NULL, 'A'),
                                 (2, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'brandB', NULL, 'B'),
                                 (3, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'brandC', NULL, 'C'),
                                 (4, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'brandD', NULL, 'D'),
                                 (5, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'brandE', NULL, 'E'),
                                 (6, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'brandF', NULL, 'F'),
                                 (7, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'brandG', NULL, 'G'),
                                 (8, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'brandH', NULL, 'H'),
                                 (9, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'brandI', NULL, 'I');
CREATE CACHED TABLE "PUBLIC"."CATEGORY"(
    "CATEGORY_IDX" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "CREATE_DT" TIMESTAMP(6) NOT NULL,
    "DELETE_DT" TIMESTAMP(6),
    "MODIFY_DT" TIMESTAMP(6) NOT NULL,
    "USE_YN" BOOLEAN NOT NULL,
    "VERSION" BIGINT NOT NULL,
    "CATEGORY_NAME" CHARACTER VARYING(255)
);
ALTER TABLE "PUBLIC"."CATEGORY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_31" PRIMARY KEY("CATEGORY_IDX");

INSERT INTO "PUBLIC"."CATEGORY" VALUES
                                    (1, TIMESTAMP '2024-07-24 20:24:21', NULL, TIMESTAMP '2024-07-24 20:24:21', TRUE, 0, U&'\c0c1\c758'),
                                    (2, TIMESTAMP '2024-07-24 20:24:21', NULL, TIMESTAMP '2024-07-24 20:24:21', TRUE, 0, U&'\c544\c6b0\d130'),
                                    (3, TIMESTAMP '2024-07-24 20:24:21', NULL, TIMESTAMP '2024-07-24 20:24:21', TRUE, 0, U&'\bc14\c9c0'),
                                    (4, TIMESTAMP '2024-07-24 20:24:21', NULL, TIMESTAMP '2024-07-24 20:24:21', TRUE, 0, U&'\c2a4\b2c8\cee4\c988'),
                                    (5, TIMESTAMP '2024-07-24 20:24:21', NULL, TIMESTAMP '2024-07-24 20:24:21', TRUE, 0, U&'\ac00\bc29'),
                                    (6, TIMESTAMP '2024-07-24 20:24:21', NULL, TIMESTAMP '2024-07-24 20:24:21', TRUE, 0, U&'\baa8\c790'),
                                    (7, TIMESTAMP '2024-07-24 20:24:21', NULL, TIMESTAMP '2024-07-24 20:24:21', TRUE, 0, U&'\c591\b9d0'),
                                    (8, TIMESTAMP '2024-07-24 20:24:21', NULL, TIMESTAMP '2024-07-24 20:24:21', TRUE, 0, U&'\c561\c138\c11c\b9ac');
CREATE CACHED TABLE "PUBLIC"."PRODUCT"(
    "PRODUCT_IDX" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 31) NOT NULL,
    "CREATE_DT" TIMESTAMP(6) NOT NULL,
    "DELETE_DT" TIMESTAMP(6),
    "MODIFY_DT" TIMESTAMP(6) NOT NULL,
    "USE_YN" BOOLEAN NOT NULL,
    "VERSION" BIGINT NOT NULL,
    "PRODUCT_DESC" CHARACTER VARYING(255),
    "PRODUCT_IMAGE" CHARACTER VARYING(255),
    "PRODUCT_NAME" CHARACTER VARYING(255),
    "PRODUCT_PRICE" FLOAT(53),
    "BRAND_IDX" BIGINT,
    "CATEGORY_IDX" BIGINT
);
ALTER TABLE "PUBLIC"."PRODUCT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("PRODUCT_IDX");

INSERT INTO "PUBLIC"."PRODUCT" VALUES
                                   (1, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is top_A', NULL, 'top_A', 11200.0, 1, 1),
                                   (2, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is outer_A', NULL, 'outer_A', 5500.0, 1, 2),
                                   (3, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is pants_A', NULL, 'pants_A', 4200.0, 1, 3),
                                   (4, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is snickers_A', NULL, 'snickers_A', 9000.0, 1, 4),
                                   (5, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is bag_A', NULL, 'bag_A', 2000.0, 1, 5),
                                   (6, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is hat_A', NULL, 'hat_A', 1700.0, 1, 6),
                                   (7, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is socks_A', NULL, 'socks_A', 1800.0, 1, 7),
                                   (8, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is accessory_A', NULL, 'accessory_A', 2300.0, 1, 8),

                                   (9, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is top_B', NULL, 'top_B', 10500.0, 2, 1),
                                   (10, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is outer_B', NULL, 'outer_B', 5900.0, 2, 2),
                                   (11, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is pants_B', NULL, 'pants_B', 3800.0, 2, 3),
                                   (12, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is snickers_B', NULL, 'snickers_B', 9100.0, 2, 4),
                                   (13, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is bag_B', NULL, 'bag_B', 2100.0, 2, 5),
                                   (14, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is hat_B', NULL, 'hat_B', 2000.0, 2, 6),
                                   (15, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is socks_B', NULL, 'socks_B', 2000.0, 2, 7),
                                   (16, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is accessory_B', NULL, 'accessory_B', 2200.0, 2, 8),

                                   (17, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is top_C', NULL, 'top_C', 10000.0, 3, 1),
                                   (18, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is outer_C', NULL, 'outer_C', 6200.0, 3, 2),
                                   (19, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is pants_C', NULL, 'pants_C', 3300.0, 3, 3),
                                   (20, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is snickers_C', NULL, 'snickers_C', 9200.0, 3, 4),
                                   (21, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is bag_C', NULL, 'bag_C', 2200.0, 3, 5),
                                   (22, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is hat_C', NULL, 'hat_C', 1900.0, 3, 6),
                                   (23, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is socks_C', NULL, 'socks_C', 2200.0, 3, 7),
                                   (24, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is accessory_C', NULL, 'accessory_C', 2100.0, 3, 8),

                                   (25, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is top_D', NULL, 'top_D', 10100.0, 4, 1),
                                   (26, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is outer_D', NULL, 'outer_D', 5100.0, 4, 2),
                                   (27, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is pants_D', NULL, 'pants_D', 3000.0, 4, 3),
                                   (28, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is snickers_D', NULL, 'snickers_D', 9500.0, 4, 4),
                                   (29, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is bag_D', NULL, 'bag_D', 2500.0, 4, 5),
                                   (30, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is hat_D', NULL, 'hat_D', 1500.0, 4, 6),
                                   (31, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is socks_D', NULL, 'socks_D', 2400.0, 4, 7),
                                   (32, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is accessory_D', NULL, 'accessory_D', 2000.0, 4, 8),

                                   (33, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is top_E', NULL, 'top_E', 10700.0, 5, 1),
                                   (34, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is outer_E', NULL, 'outer_E', 5000.0, 5, 2),
                                   (35, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is pants_E', NULL, 'pants_E', 3800.0, 5, 3),
                                   (36, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is snickers_E', NULL, 'snickers_E', 9900.0, 5, 4),
                                   (37, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is bag_E', NULL, 'bag_E', 2300.0, 5, 5),
                                   (38, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is hat_E', NULL, 'hat_E', 1800.0, 5, 6),
                                   (39, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is socks_E', NULL, 'socks_E', 2100.0, 5, 7),
                                   (40, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is accessory_E', NULL, 'accessory_E', 2100.0, 5, 8),

                                   (41, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is top_F', NULL, 'top_F', 11200.0, 6, 1),
                                   (42, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is outer_F', NULL, 'outer_F', 7200.0, 6, 2),
                                   (43, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is pants_F', NULL, 'pants_F', 4000.0, 6, 3),
                                   (44, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is snickers_F', NULL, 'snickers_F', 9300.0, 6, 4),
                                   (45, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is bag_F', NULL, 'bag_F', 2100.0, 6, 5),
                                   (46, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is hat_F', NULL, 'hat_F', 1600.0, 6, 6),
                                   (47, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is socks_F', NULL, 'socks_F', 2300.0, 6, 7),
                                   (48, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is accessory_F', NULL, 'accessory_F', 1900.0, 6, 8),

                                   (49, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is top_G', NULL, 'top_G', 10500.0, 7, 1),
                                   (50, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is outer_G', NULL, 'outer_G', 5800.0, 7, 2),
                                   (51, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is pants_G', NULL, 'pants_G', 3900.0, 7, 3),
                                   (52, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is snickers_G', NULL, 'snickers_G', 9000.0, 7, 4),
                                   (53, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is bag_G', NULL, 'bag_G', 2200.0, 7, 5),
                                   (54, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is hat_G', NULL, 'hat_G', 1700.0, 7, 6),
                                   (55, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is socks_G', NULL, 'socks_G', 2100.0, 7, 7),
                                   (56, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is accessory_G', NULL, 'accessory_G', 2000.0, 7, 8),

                                   (57, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is top_H', NULL, 'top_H', 10800.0, 8, 1),
                                   (58, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is outer_H', NULL, 'outer_H', 6300.0, 8, 2),
                                   (59, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is pants_H', NULL, 'pants_H', 3100.0, 8, 3),
                                   (60, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is snickers_H', NULL, 'snickers_H', 9700.0, 8, 4),
                                   (61, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is bag_H', NULL, 'bag_H', 2100.0, 8, 5),
                                   (62, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is hat_H', NULL, 'hat_H', 1600.0, 8, 6),
                                   (63, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is socks_H', NULL, 'socks_H', 2000.0, 8, 7),
                                   (64, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is accessory_H', NULL, 'accessory_H', 2000.0, 8, 8),

                                   (65, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is top_I', NULL, 'top_I', 11400.0, 9, 1),
                                   (66, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is outer_I', NULL, 'outer_I', 6700.0, 9, 2),
                                   (67, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is pants_I', NULL, 'pants_I', 3200.0, 9, 3),
                                   (68, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is snickers_I', NULL, 'snickers_I', 9500.0, 9, 4),
                                   (69, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is bag_I', NULL, 'bag_I', 2400.0, 9, 5),
                                   (70, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is hat_I', NULL, 'hat_I', 1700.0, 9, 6),
                                   (71, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is socks_I', NULL, 'socks_I', 1700.0, 9, 7),
                                   (72, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, TRUE, 0, 'This is accessory_I', NULL, 'accessory_I', 2400.0, 9, 8);

ALTER TABLE "PUBLIC"."PRODUCT" ADD CONSTRAINT "PUBLIC"."FK8LXA31LCQ24P242BSPKXAJ2OX" FOREIGN KEY("BRAND_IDX") REFERENCES "PUBLIC"."BRAND"("BRAND_IDX") NOCHECK;
ALTER TABLE "PUBLIC"."PRODUCT" ADD CONSTRAINT "PUBLIC"."FKEWU5WQW9P0NHLOIL4YJQOM38J" FOREIGN KEY("CATEGORY_IDX") REFERENCES "PUBLIC"."CATEGORY"("CATEGORY_IDX") NOCHECK;
